workflows:
  android-workflow:
    name: Dual Live Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 17
      groups:
        - keystore_credentials
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build APK
        script: | 
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - mohammedauwalnasara@gmail.com
