workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60

    environment:
      vars:
        FLUTTER_CHANNEL: stable

    scripts:
      - name: Build APK
        script: |
          cd android-app
          ./gradlew assembleDebug

    artifacts:
      - android-app/app/build/outputs/apk/debug/app-debug.apk