workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    scripts:
      - name: Build APK
        script: ./android-app/gradlew assembleDebug
    artifacts:
      - android-app/app/build/outputs/apk/debug/app-debug.apk
