workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_CHANNEL: stable
      android:
        gradle_version: 9.2
        jdk: openjdk-21
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
